### PR TITLE
From week_07 day_03 HW pull request

### PR DESCRIPTION
**Pull request by howardmann**
**Week_07 day_03 HW: jQuery AJAX Flickr**

**How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible**
8/10

**Was there anything that you struggled with?**
Caching and accessing jQuery variables. One minor thing I couldn't do was change the css visibility of the next and prev buttons from hidden and visible, so I resorted to fadeIn and fadeOut but doesn't have the same effect.

**Is there anything that you'd like some further information on?**
I would like to find time to learn how to create my own API. Any references/ links to best practices for creating your own API and naming routes would be helpful. Also any reference recommendations on scroll driven animations would be helpful.

**Roughly how long did it take?**
A few hours.

### CODE REVIEW

**Comment by howardmann** [comment]
**Week_10 day_01 HW: jQuery plugin**

How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible
6/10

**Was there anything that you struggled with?**
Not particularly. Objective was to design a very simple jQuery image slider plugin.

**Is there anything that you'd like some further information on?**
Any best practice jQuery plugin README documentation would be cool.

**Roughly how long did it take?**
A few hours.

[Click here to see my separate github repo and README] (https://github.com/howardmann/simple_slider)

**Comment by howardmann** [comment]
**Week_10 day_01 HW: jQuery Plugin**

**How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible**
6/10

**Was there anything that you struggled with?**
Not particularly. Objective was to create a very simple image slider plugin.

**Is there anything that you'd like some further information on?**
Any examples of writing best practice jQuery plugin READMEs would be greatly appreciated.

**Roughly how long did it take?**
A few hours.

[Click here to see separate github repo and README](https://github.com/howardmann/simple_slider)

**Comment by cjbarnaby** [comment]
Hey Howie, 

For scroll-driven animations, check out [Scroll Magic](http://scrollmagic.io/) and [skrollr](https://prinzhorn.github.io/skrollr/) - I haven't actually used the first one, but it's pretty popular and is specifically designed for scroll-driven animations. The latter is what I used for my portfolio.

As far good jQuery plugin READMEs go, the Scroll Magic one is pretty good. Maybe a bit too much info. Was just looking at [typeaheadJS's repo](https://github.com/twitter/typeahead.js/), and that's a good example, IMHO.

Re: resources for creating your own API - I'll have a chat to Jack, but this might be a good starting point if you'd consider moving to Rails 5 - [Rails 5 - Using Rails for API-only applications](http://guides.rubyonrails.org/api_app.html). It's a guide for Rails 5 and, unfortunately, there's no equivalent doc in the Rails 4.2 docs, since Rails 5 introduced a new API mode (which you can use by adding the --api flag to your `rails new` command). There are a _lot_ of articles out there about building an API with this new feature of Rails 5, which would come in handy.

**Comment by cjbarnaby** [comment]
(sorry, just realised that first PR was from several weeks ago)

**Comment by howardmann** [comment]
Awesome,

Thanks for the resources Badger. I will definitely check out.

Regards,

Howie

**Pull request merged**
