### PR TITLE
Day 02 Computer scientist CSS & Day03 DOM manipulation exercise

### PR DESCRIPTION
**Pull request by howardmann**
**Computer scientist CSS homework**

**How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;**
7/10

**Was there anything that you struggled with?;**
Generally understanding positioning of CSS, particularly relative and absolute and how containers are placed within other containers. I think I need to practice it more to understand.
Specifically my styling of the background images on each profile was not DRY, as you will see I repeated the code each time for the 3 pages; any suggestions to clean this up once would be much appreciated.

**Is there anything that you'd like some further information on?;**
Materials on background image manipulation would be very helpful, including cropping, positioning etc. I struggled to understand the posts on CSS tricks.

**Roughly how long did it take?**
Took a lot of trial and error

### CODE REVIEW

**Comment by howardmann** [comment]
**DOM manipulation exercise arrays**

**How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;**
7/10

**Was there anything that you struggled with?;**
Remembering to switch between JS and CSS style selector rules.

**Is there anything that you'd like some further information on?;**
Not at this stage. I need to spend more time understanding the concepts of DOM manipulation and animation.

**Roughly how long did it take?**
30 mins

**Comment by howardmann** [comment]
Super Cat Mario homework

Awesome fun; But not actively looking for feedback on this code (a lot of embarrassing hacks). I would much prefer feedback on Project Zero jQuery (see comment below).

**Comment by howardmann** [comment]
**Ruby exercises**

**Week_04 day_01 homework**
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;
5/10

**Was there anything that you struggled with?;**
Remembering Ruby syntax.

**Is there anything that you'd like some further information on?;**
Not at this stage. Will seek more feedback following Ruby MTA exercise after learning about Ruby collections.

**Roughly how long did it take?**
2 hours

**Comment by howardmann** [comment]
**Week_04 day_02 homework MTA Ruby**
**How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;**
4/10

**Was there anything that you struggled with?;**
Not particularly. Much easier the second time around using Ruby, and also having had more practice with coding JavaScript. Practicing the spaceship comparator was fun, not needed for this exercise, but I can see it being useful in future.

**Is there anything that you'd like some further information on?;**
Again not at this stage with Ruby. Not until we go through Classes and Modules and how they interact with what we have learnt in the last 2 days.

**Roughly how long did it take?**
1 hour

**Comment by howardmann** [comment]
**Week_04 day_03 homework Sinatra Movie I**

**How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;**
7/10

**Was there anything that you struggled with?;**
This was a challenging topic and homework exercise in understanding the GET, params and form methods and hashes. Requires more memorisation I feel vs. other topics, which I am sure I will forget if I don't continue practicing. Most challenging was bringing together Ruby, CSS and JavaScript to Sinatra.

**Is there anything that you'd like some further information on?;**
More conceptual background information on persistence of data across methods would be helpful. A lot of the hash data I was able to access and manipulate in pry I could not do once written in Sinatra. Binding helped to debug, but I am not 100% clear on why stored variables cannot persist between get request methods.

**Comment by howardmann** [comment]
Priority feedback request.

Hi @cjbarnaby Badger, in terms of prioritising feedback across my work thus far, It would be great if you could have a glance at my Project Zero tic tac toe game in my github repo. In particular I had a lot of trouble with jQuery in terms of organising the code/ logic and being able to confidently modify features without breaking everything. Happy to discuss in person if its easier.

Thanks in advance.

**Comment by howardmann** [comment]
**Week_04 day_04 homework Sinatra CRUD app**

**How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;**
9/10

**Was there anything that you struggled with?;**
This was again challenging to remember the workflow and interaction between Ruby and SQL.

**Is there anything that you'd like some further information on?;**
Not at this stage until we get into Ruby.

**Comment by howardmann** [comment]
**Week_05 day_01 homework Rails Game and CRUD practice**

**How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;**
5/10

**Was there anything that you struggled with?;**
Spent more time practicing basic Rails CRUD app following class code-along. Challenge remains understanding the security params happening behind the scenes.

**Is there anything that you'd like some further information on?;**
Not at this stage.

**Roughly how long did it take?;**
Spent very little time on the game homework (hence the poor naming of controllers and routes). Spent most of the time on recreating a basic Rails CRUD app for a books database.

**Comment by howardmann** [comment]
**Week_05 day_02 homework Rails CRUD again**

**How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;**
7/10

**Was there anything that you struggled with?;**
Rails migrations, altering tables and rollbacks. I had an issue with creating a model for the singular Hero which rails was not able to pluralise to 'Heroes' and instead did 'Heros' which became confusing as it was able to pluralise correctly in the resources. Hence lots of conflicts with database, paths and form_for built in's. Long story short, lot's of database resets, rails helpers becoming not so helpful, and resorting to custom paths. Managed to get it to work but only thanks to Jack going through the hard way in class not relying on helpers and shortcuts.

**Is there anything that you'd like some further information on?;**
Not at this stage.

**Roughly how long did it take?;**
A few hours.

**Comment by howardmann** [comment]
**Week_05 day_03 homework Rails has_many, belongs_to, has_many through models**

**How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;**
7/10

**Was there anything that you struggled with?;**
Good practice with multiple model associations and keeping track of associations.

**Is there anything that you'd like some further information on?;**
Not at this stage. I will aim to read up on all the rails migration and helper documentation and gitbook material

**Roughly how long did it take?;**
Longer, given the multiple database models and test script to be written

**Comment by howardmann** [comment]
**Week_07 day_01 homework OMDB DOM XHR ajax request**

**How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;**
8/10

**Was there anything that you struggled with?;**
Remembering the XHR readystates and getting back into JavaScript and jQuery 

**Is there anything that you'd like some further information on?;**
Not at this stage. My focus at this stage is on understanding AJAX and not on CSS styling or animations.

**Roughly how long did it take?;**
A few hours.

**Comment by cjbarnaby** [comment]
Hey Howie, 

Sorry for the delay in getting feedback on your homework. To be honest, you're killing it, so I'm trying to prioritize project feedback and feedback for those students who are struggling more than yourself. Having said that, I plan to get back into reviewing _everyone's_ homework every day. 

You asked for feedback on a few specific things, so I'll address those here at least. 

## Background images

This [css-tricks post](https://css-tricks.com/almanac/properties/b/background-image/) (and the 'related' links at the bottom of the page) is a really good starting point for working with background images. 

You can't really position a background image (itself) in the way you can with the traditional traditional visual formatting model's positioning scheme, since the background is not a seperate image element. 

As far as a few background-image tips/techniques goes, here's a few things that I think are handy to know:
- You can layer background-images (especially useful when you've got a bunch of pngs with a transparent background). This is done by giving the background-image property [multiple, comma-separated values](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Using_CSS_multiple_backgrounds). eg `background-image: url(badger.png), url(wolf.png);`
- You can add color fallbacks to a background-image. This is done by putting a valid color value after the background-image url. eg `background-image: url(badger.png) blue`
- You can [position a background image](https://css-tricks.com/almanac/properties/b/background-position/) in a way that's similar to positioning a positioned element in CSS. You can specify any valid CSS length values (px, em, rem, %) as well as use keywords like `top`, `top right`, etc. 
- You cannot change the opacity of a background-image without affecting the opacity of the element itself (along with all its children). A common workaround is to create to elements that are the same size - the first element is your background image's container. Apply the background-image and opacity to that element, and give it `position: relative`. The second element contains the content (that you don't want to change the opacity of). Make this `position: absolute` with `top: 0; left: 0` (to make sure it sits directly over the background image div). 
- Probably the most common thing you'll want to do with a background image is set its `background-size`. There's only three values you need to remember:
  - `background-size: auto` (the default) - just whack it in there;
  - `background-size: cover` - make the image cover the entire container, even if it means cropping or stretching the image; 
  - `background-size: contain` - show the whole image, even if that means leaving some gaps on one or more edges. 
- When you're dealing with images of an unknown size (perfect example - user profile images), it's really common to set the image as the background-image of a div that has fixed dimensions, and giving that a `background-image: cover`, rather than setting the image in an `img` element. 

## Rails pluralization

You can specify custom pluralization/singularization rules for your tables/models using Rails' inflector module. tbh, I've never had to do this, but it looks like it's relatively painless. [Here's a blog post I found](https://4loc.wordpress.com/2009/04/09/inflector-rails-pluralization/), and here's the [api dock docs on the module](http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html).

## Variable scope in Ruby

I reckon you're probably across this by now, but - if I'm interpreting your issue correctly ("I am not 100% clear on why stored variables cannot persist between get request methods."), just remember that in Ruby, a local variable's scope is limited to the `do` / `end` block in which it's defined (it's  [a little more complicated than that](https://cjbarnaby.gitbooks.io/wdi-16/content/week_04/wk04_day05.html#ruby---variable-scope), but in this case, where our routes are all `do` / `end` blocks, it's gonna be that), and HTTP is a [stateless protocol](https://en.wikipedia.org/wiki/Stateless_protocol), meaning that each request is treated as a new transaction between the client and server, and state is not preserved between request/responses. Enter things like the `session` and `flash` hashes in Rails, which allow us to preserve some information about state between requests.

**Pull request merged**
