### PR TITLE
Week_01 homework

### PR DESCRIPTION
**Pull request by howardmann**
Week_01 Javascript homework

How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;
- (7/10). Found Hangman and JS Bank exercises most challenging .

Was there anything that you struggled with?;
- Hangman was challenging. Found a solution using regular expression matches but was unhappy with the solution and found it too verbose. Really liked fellow GA Arpan's solution and have included for future reference.

Is there anything that you'd like some further information on?;
- Could you please review my JS Bank solution. Would appreciate comments and ability to reduce code and improve readability. Query if there is a better way to search if a specific account exists int the bank.accounts array of objects.

Roughly how long did it take?
- Completed before class next day. Day04 homework and exercises was a big ramp up from Day01-03

Thanks Badger!

### CODE REVIEW

**Comment by howardmann** [comment]
MTA assignment

How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;
-MTA difficulty 8/10

Was there anything that you struggled with?;
-Using multiple functions to goForward and goBackward and accessing the Object property names

Is there anything that you'd like some further information on?;
-Any further ways to refactor and reduce code in file mtaRefactor.js. I felt my code was repetitive in terms of writing out the indexOf positions multiple times

Roughly how long did it take?
-4 hours before refactoring and another 3 hours to refactor using multiple functions

**Comment by howardmann** [comment]
CSS exercises

How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;
-MTA difficulty 8/10

Was there anything that you struggled with?;
-Making elements and images centre harder than expected. Lots of bugs to work through

Is there anything that you'd like some further information on?;
-Not really. Just feel like I should practice more

Roughly how long did it take?
-5 frustrating hours

**Comment by cjbarnaby** [comment]
Hey Howie, 

Really great work on the homework so far! You definitely seem to have a solid handle on everything. 

I'll send the comments on each night's homework separately. 

## Strings

All really good, just a few little suggestions/observations:

#### squareNumber
- **Type coercion** - if one of the operands in an expression that includes the unary (`+`) operator is a string, any numbers (etc) will be coerced to strings, and the `+` will concatenate the strings. Since the expression evaluates to a string (ie, `typeof(msg) //=> "string"), there's no need to call`msg.toString();`.

#### areaOfCircle
- **Math.pow** - while `var result = pi*radius*radius;` is definitely easier to type and easier to read, I just thought I'd make sure you're aware of the Math.pow() method, which is useful for bigger exponents, or exponents with variable values: `Math.pow(radius, 2)`. Like I said, I'd prefer your approach in this instance. Just sayin'.

#### mixUp
- **Readability** - Whitespace is your friend. JS ignores it, but it makes your code a lot more readable. I think it's a good idea to put spaces around all operators, so instead of 

``` js
var sliceA = B.charAt(0)+B.charAt(1)+A.slice(2);
console.log(sliceA+" "+sliceB);
```

I would suggest: 

``` js
var sliceA = B.charAt(0) + B.charAt(1) + A.slice(2);
console.log( sliceA + " " + sliceB );
```

**Comment by cjbarnaby** [comment]
## Bank

Again, really good work.

First, re: your specific question _"Query if there is a better way to search if a specific account exists in the bank.accounts array of objects."_

Your code:

``` js
  checkAccount: function(value) {
      var found = false;
      for (var i=0; i<this.accounts.length; i++) {
        if (this.accounts[i]["name"] === value) {
          found = true;
          break;
        }
      }
      return found;
  },
```

You could use Array.some():

``` js
  checkAccount: function(value) {
    return found = this.accounts.some(function(i) {
      return (i.name === value);
    });
  },
```

`.some` takes an array and, for each (`i`th) element in the array, tests the condition in the block, returning true (and `break`ing) if the condition is satisfied. 

In terms of **DRY**ing up your code, it looks pretty good to me. Opportunities to refactor would probably present themselves if you'd gotten into the withdraw and transfer functions, but as it is, there's really not any duplication in there. Nice job.

**Comment by cjbarnaby** [comment]
## Arrays

All really good stuff. I'd avoid using the spread operator (`...`) (eg `Math.max(...numArr)`). It's pretty new and isn't well supported across browsers (esp mobile).

**Comment by howardmann** [comment]
Thanks Badger,

Really appreciate you taking the time to go through my work. I can barely stand going through my own code.

Also, thank you for outlining the Array.some function, there have definitely been times I could have used this and I will practice for future use.

Keep up the great schooling!

Howie

**Comment by cjbarnaby** [comment]
## MTA

Good job on MTA - and cool to see how you went about refactoring. 
- **Iterating through objects** - I wasn't really sure what this was supposed to do:

``` js
  // Naming properties
  for (var prop in Subway) {
    var startName = startLine;
    var endLine = endLine;
  }
```

That'll just repeatedly assign the value of the `startLine` variable to the variable`startName`, and assign `endLine` the value of itself three times (the Subway object having three key:value pairs). 

I'm thinking this was probably the start something you didn't end up needing/completing, but if you want more info on the JS object 'for' statement, check out the [MDN JS reference's entry](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/for...in) on it. Basically, it lets you iterate over the properties of an object (in much the same way as the JS array for loop does), with an arbitrary value ('prop' in the example below) assigned to the a property of the object on each iteration. 

``` js
var obj = {a:1, b:2, c:3};

for (var prop in obj) {
  console.log("obj." + prop + " = " + obj[prop]);
}
// "obj.a = 1"
// "obj.b = 2"
// "obj.c = 3"
```

**Variable names** - Good use of variable names throughout - descriptive and consistent. That might sound like a minor point, but you'd be surprised, and it makes your code a whole lot more predictable and readable for other developers. A very minor thing, but the convention is to use capital first letters for constructors and factories (some suggest reserving it exlusively for constructors). Obviously doesn't affect your code at all, but if another developer sees `Subway`, the first thing they think is likely to be "is that a constructor?". 

**Refactoring** - In terms of refactoring, the first thing I would look for is code duplicated between functions. Your `goBackward` and `goForward` functions are pretty similar - there are 8 lines of code, and 6 of them are identical. The only substantial difference is whether you increment or decrement in your `for` loop, which turns on whether the `startStop >`endStop`. A quick refactor would be to reduce this to a single function, add an additional parameter for the direction (say,`direction`), and have a conditional (`if (direction === 'forward') {}`) which determines whether the loop decrements or increments. 

You could probably even refactor this further by reversing the stations array for backwards journeys, which - I think - should mean you can just increment in your loop (for both forwards and backwards journeys). One issue with that is that JavaScript's native `Array.reverse()` method is a mutator method - it modifies the array in place, changing the order of your stations, which you don't want. Here's a pretty sweet little one liner for reversing an array and storing it in a new variable without mutating the original array: `var reverseArray = [].concat(array).reverse();`

I'm not really sure that you're going to be able to do much to reduce your code finding the indexOf stations. The only thing I can think of would be to use the `arguments` object (check out the GitBook  notes from Week 1 Day 5), but I really don't think it's worth it - it will just make the code more obscure and probably only save you a line of code. 

**Edge cases** - You might want to have a think about how to resolve this issue in the console: `You must travel through the following stops on the the L line: .` - if you're travelling backwards, you're not capturing the first stop (that was one of the outputs for `planTrip("L","1st","6","Grand Central"`).

Good job on this!

**Comment by cjbarnaby** [comment]
## HTML Labs

I'm going to be pretty brief with this feedback, since everything (plus your computer scientist fansite) suggests you're more than coping with HTML/CSS now :) 
- **Filters** - really nice use of filters & hover states for the social media icon. 
- **Pixel perfect** - about as close to pixel perfect as you can get. Nice.
- **Centering images** - your approach of changing the image's display property to `display: block` and setting `margin: 0 auto` works fine, but images are treated as text-like elements, so instead, you could have given the parent div (`<div class="banner">`) the attribute `text-align: center` and that would have worked as well.
- **Container width** - Generally, it's better to give container divs a `max-width`, rather than an explicit `width`. That way content in an inline phrasing context (like text, images, etc) will minimize and, potentially, avoid the need to scroll to see the full width of the page.

**Pull request merged**
